---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  # - 1.8.7  --- nothing seems to work with this version
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.5.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.6.2" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.5" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.5" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.8.4" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.8.4" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.2.3" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.3.1" STRICT_VARIABLES=yes
matrix:
  exclude:
    # ruby 1.8.7
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.2.3" STRICT_VARIABLES=yes
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.3.1" STRICT_VARIABLES=yes
    
    # Ruby 2.2.3
    # NameError: uninitialized constant Syck
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.5.1" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.6.2" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.7.5" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.8.4" STRICT_VARIABLES=yes
